#pragma once

#include "../types.h"

inline void plotTracker(const TrackerStruct& Tracker)
{
	const double averagePercent = (double)Tracker.averagePercent;
	
    if constexpr (!(TRACK_WALL_FORCE || TRACK_ROTOR_FORCE || TRACK_OPEN_BOUNDARIES))
        return;

    const int count = Tracker.iterationsFinished;
    if (count == 0) return; // No recorded history yet.

    const std::string script = "../../include/plotter/plotTracker.py";
    
    using Histories = std::array<const FloatArray2DTypeCPU*, 6>;

    auto exportObject = [&](const char* kind, const char* title, int id,
                            const Histories& histories)
    {
        std::cout << "Exporting " << title << " ID " << id
                  << " tracker ... " << std::flush;

        // Unique shared-memory file avoids collisions between simulations.
        char dataPath[] = "/dev/shm/lbmTrackerXXXXXX";
        const int descriptor = mkstemp(dataPath);
        if (descriptor < 0)
            throw std::runtime_error("Cannot create tracker shared-memory file");
        FILE* fp = fdopen(descriptor, "wb");
        if (!fp) {
            close(descriptor);
            std::remove(dataPath);
            throw std::runtime_error("Cannot open tracker shared-memory stream");
        }

        try {
            const std::int32_t header[2] = {
                static_cast<std::int32_t>(count), static_cast<std::int32_t>(id)
            };
            bool ok = std::fwrite(header, sizeof(header[0]), 2, fp) == 2;
            // Gather via operator(): do not assume a particular NDArray stride.
            std::vector<float> row(count);
            for (const auto* history : histories) {
                for (int sample = 0; sample < count; ++sample)
                    row[sample] = (*history)(id, sample);
                if (std::fwrite(row.data(), sizeof(float), row.size(), fp) != row.size())
                    ok = false;
            }
            const int closeStatus = std::fclose(fp);
            fp = nullptr;
            if (!ok || closeStatus != 0)
                throw std::runtime_error("Cannot write complete tracker payload");

            // Synchronous: Python finishes reading and exporting before reuse.
            // Paths here are fixed or generated by mkstemp, not user input.
            const std::string command = "python3 '" + script + "' " + kind
                + " '" + dataPath + "' --average-percent "
                + std::to_string(averagePercent);
            if (std::system(command.c_str()) != 0)
                 std::cerr << "Warning: tracker plot failed for "
					<< title << " ID " << id
					<< ". Continuing simulation.\n";
        }
        catch (...) {
            if (fp) std::fclose(fp);
            std::remove(dataPath);
            throw;
        }
        std::remove(dataPath);
    };

    if constexpr (TRACK_OPEN_BOUNDARIES) {
        const Histories histories = {
            &Tracker.normalVelocityArray, &Tracker.massFlowArray,
            &Tracker.momentumThrustArray, &Tracker.pressureArray,
            &Tracker.pressurePowerArray, &Tracker.normalKineticPowerArray
        };
        for (int id = 0; id < Tracker.openBCCount; ++id)
            exportObject("boundary", "Boundary", id, histories);
    }
    if constexpr (TRACK_WALL_FORCE) {
        const Histories histories = {
            &Tracker.wallFxArray, &Tracker.wallFyArray, &Tracker.wallFzArray,
            &Tracker.wallTxArray, &Tracker.wallTyArray, &Tracker.wallTzArray
        };
        for (int id = 0; id < Tracker.wallCount; ++id)
            exportObject("wall", "Wall", id, histories);
    }
    if constexpr (TRACK_ROTOR_FORCE) {
        const Histories histories = {
            &Tracker.rotorFxArray, &Tracker.rotorFyArray, &Tracker.rotorFzArray,
            &Tracker.rotorTxArray, &Tracker.rotorTyArray, &Tracker.rotorTzArray
        };
        for (int id = 0; id < Tracker.rotorCount; ++id)
            exportObject("rotor", "Rotor", id, histories);
    }
}
